### ISSUE TITLE
J'aimerais trouver un thème ou une extension Firefox qui me permette de bien identifier visuellement l'onglet actif

### ISSUE THREAD

**Issue by stephane-klein** [stephane-klein/dotfiles#56]
J'aimerais trouver un thème ou une extension Firefox qui me permette de bien identifier visuellement l'onglet actif.

**Comment by GllmR** [comment]
Perso, j'utilise "matte-black-theme", principalement pour cette raison.

https://github.com/elibroftw/matte-black-theme#matte-black-type-themes-for-chromium-and-firefox

Petite capture : 

![image](https://user-images.githubusercontent.com/56537238/221008911-d989ce75-4efc-4f95-bf04-07c07e5aff37.png)

**Comment by stephane-klein** [comment]
Merci @GllmR , je vais essayer cela 👍

**Comment by stephane-klein** [comment]
J'ai choisi https://github.com/elibroftw/matte-black-theme/releases 🙂
